* Words after a switch: SET COMPATIBLE's PROMPT or NOPROMPT is its second answer
? SET("COMPATIBLE"), SET("COMPATIBLE", 1)
SET COMPATIBLE OFF NOPROMPT
? SET("COMPATIBLE"), SET("COMPATIBLE", 1)
SET COMPATIBLE OFF PROMPT
? SET("COMPATIBLE"), SET("COMPATIBLE", 1)
SET COMPATIBLE OFF NOPROMPT
SET COMPATIBLE OFF
? SET("COMPATIBLE"), SET("COMPATIBLE", 1)
SET TALK OFF NOWINDOW
? SET("TALK"), SET("TALK", 1)
